name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          
      - name: Install dependencies
        run: |
          npm install
          npm install react-ga4@latest --save
      
      - name: Debug environment variables
        run: |
          echo "Checking environment variables..."
          echo "VITE_GROQ_API_KEY exists: ${{ secrets.VITE_GROQ_API_KEY != '' }}"
          echo "VITE_GROQ_API_URL exists: ${{ secrets.VITE_GROQ_API_URL != '' }}"
          echo "VITE_GROQ_MODEL exists: ${{ secrets.VITE_GROQ_MODEL != '' }}"
        
      - name: Build
        run: npm run build
        env:
          VITE_EMAILJS_SERVICE_ID: ${{ secrets.VITE_EMAILJS_SERVICE_ID }}
          VITE_EMAILJS_TEMPLATE_ID: ${{ secrets.VITE_EMAILJS_TEMPLATE_ID }}
          VITE_EMAILJS_PUBLIC_KEY: ${{ secrets.VITE_EMAILJS_PUBLIC_KEY }}
          VITE_GROQ_API_KEY: ${{ secrets.VITE_GROQ_API_KEY || '' }}
          VITE_GROQ_API_URL: ${{ secrets.VITE_GROQ_API_URL || 'https://api.groq.com/openai/v1/chat/completions' }}
          VITE_GROQ_MODEL: ${{ secrets.VITE_GROQ_MODEL || 'openai/gpt-oss-120b' }}
          VITE_GA_TRACKING_ID: "G-MD5CG3N4WF"
          
      - name: Create .nojekyll file
        run: touch dist/.nojekyll
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true